In [2]:
import numpy

In [3]:
numpy.__version__

'1.18.1'

In [4]:
import numpy as np

## Python List的特点

In [18]:
L=[i for i in range(10)]
L[5] = "2w"
L

[0, 1, 2, 3, 4, '2w', 6, 7, 8, 9]

In [19]:
import array

In [20]:
arr=array.array('i',{i for i in range(10)})
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[5]

5

In [22]:
arr[5]=111

## numpy.array

In [24]:
nparr=np.array([i for i in range(10)])

In [25]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
nparr[5]

5

In [28]:
nparr[5]=100

In [29]:
nparr.dtype

dtype('int64')

In [30]:
nparr[5]=5.0

In [31]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
nparr2=np.array([1,2,3.0])

In [33]:
nparr2.dtype

dtype('float64')

## 其他创建numpy.array的方法

In [36]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros(10).dtype

dtype('float64')

In [38]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.zeros(shape=[3,5],dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [41]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.full([3,5],666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [44]:
np.full(fill_value=12,shape=10)

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

## arange

In [46]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [47]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## linspace

In [49]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [50]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [51]:
np.random.randint(0,10)

1

In [54]:
np.random.randint(0,10,size=10) #取不到10

array([6, 2, 2, 1, 5, 5, 1, 4, 1, 7])

In [55]:
np.random.randint(0,10,size=[3,5])

array([[2, 6, 7, 2, 8],
       [4, 1, 5, 6, 1],
       [3, 5, 7, 1, 0]])

In [58]:
np.random.normal()

-0.05432931884976687

In [59]:
np.random.normal(0,1,[3,5])

array([[-0.20643198,  1.57916668,  0.32679648, -0.97628718, -0.24137969],
       [ 1.3705156 ,  1.61126346, -0.50406941,  0.26020302, -1.4835777 ],
       [ 0.18422547,  0.93360268,  1.80972711,  2.70570609, -0.20965027]])

## Numpy.array基本操作

In [60]:
x=np.arange(10)

In [61]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
X=np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
x.ndim

1

In [65]:
X.shape

(3, 5)

In [67]:
X[2,3]

13

In [70]:
x[0:3]

array([0, 1, 2])

In [71]:
x[5:]

array([5, 6, 7, 8, 9])

In [72]:
x[::2]

array([0, 2, 4, 6, 8])

In [73]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [74]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

## 合并操作

In [75]:
x=np.array([1,2,3])

In [76]:
y=np.array([3,2,1])

In [77]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [80]:
A=np.array([[1,2,3],[4,5,6]])

In [82]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])