In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
digits=datasets.load_digits()
X=digits.data
y=digits.target.copy()
y[digits.target==9]=1
y[digits.target!=9]=0


In [2]:
from sklearn.model_selection import train_test_split

In [3]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=666)

In [4]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)
y_predict=log_reg.predict(X_test)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [5]:
from sklearn.metrics import f1_score
f1_score(y_test,y_predict)

0.8674698795180723

In [6]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_predict)

array([[403,   2],
       [  9,  36]])

In [7]:
from sklearn.metrics import precision_score
precision_score(y_test,y_predict)

0.9473684210526315

In [8]:
from sklearn.metrics import recall_score
recall_score(y_test,y_predict)

0.8

In [9]:
log_reg.decision_function(X_test)

array([-21.45985612, -32.95369325, -16.40089372, -79.9179075 ,
       -48.17449518, -24.21735792, -44.76578369, -24.22771585,
        -1.22644781, -19.07604317, -65.863024  , -50.97148327,
       -30.88918504, -46.11559963, -37.39814384, -29.70283342,
       -36.89572789, -82.86794195, -37.770388  ,  -9.86191397,
        -9.26348365, -85.2776449 , -16.74413548, -45.34499943,
        -4.96823072, -48.46743432, -11.66947651, -37.20331773,
       -25.15893173, -13.49371587, -16.58856566, -28.869577  ,
       -34.47732498, -28.54994339,  -8.07904044,  -4.60793401,
       -21.65097259, -21.82095984, -30.93464591, -23.48254674,
       -26.95989197, -62.22879763, -37.70222853, -66.33146848,
       -20.08024127, -16.65249742, -18.09249536, -21.62839338,
       -29.05799357, -19.74592843,   2.56715933,   7.73311621,
       -34.78482342, -42.74279261, -25.87953121, -34.88100695,
        -7.61178395, -49.71066592, -51.58449001,  19.7011737 ,
       -10.13093825, -32.09150486, -11.55168132,  -1.62

In [10]:
log_reg.decision_function(X_test)[:10]

array([-21.45985612, -32.95369325, -16.40089372, -79.9179075 ,
       -48.17449518, -24.21735792, -44.76578369, -24.22771585,
        -1.22644781, -19.07604317])

In [11]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
decision_score=log_reg.decision_function(X_test)

In [13]:
np.min(decision_score)

-85.76652882645814

In [14]:
np.max(decision_score)

19.97568937249484

In [18]:
y_predict_2=np.array(decision_score>=5,dtype='int')

In [19]:
confusion_matrix(y_test,y_predict_2)

array([[404,   1],
       [ 21,  24]])